### ISSUE TITLE
Octoscreen 2.7.0 don't recognize The octoscreen plugin 2.6.0 installed 

### ISSUE THREAD

**Issue by NicoIT31** [Z-Bolt/OctoPrint-Z-Bolt-OctoScreen#16]
Thanks for your update, but i think the current version of octoscreen plugin is not recognized from the octoscreen 2.7.0

![Immagine 2021-03-28 104051](https://user-images.githubusercontent.com/32997613/112746867-243f2200-8fb2-11eb-88ce-42003bc3e261.jpg)

Thanks.

Nicola.

**Comment by JeffB42** [comment]
Confirmed, kind of...
On the system I regularly dev with, this works fine.  I tried on a different system and was able to reproduce the bug.  Then I rebooted the system and it worked, then rebooted again and it was back to being unrecognized.  I'm going go move this bug over to https://github.com/Z-Bolt/OctoScreen/issues since this is a bug in OctoScreen and not the plug-in, and posting there will have a little more visibility and let other users know there's an issue.
