### ISSUE TITLE
Request: Please remove LESS and CSS files

### ISSUE THREAD

**Issue by JeffB42** [Z-Bolt/OctoPrint-Z-Bolt-OctoScreen#5]
Request: Please remove LESS (theme.less and variables.less) and CSS (main.css, theme.css, theme.css.map) files

In order to customize OctoScreen, one must install the OctoPrint-Z-Bolt-OctoScreen plugin.  Upon installation (and then reboot), stylings & layout defined by Themeify are clobbered.  The ReadMe for OctoPrint-Z-Bolt-OctoScreen says it is:
_"Plugin Provides settings management for OctoScreen"_

Since it's a settings manager for OctoScreen, why is it defining & overriding CSS?  I think an easy solution is to remove (or empty) the LESS and CSS files in OctoPrint-Z-Bolt-OctoScreen.

**Comment by Protean-Man** [comment]
I'm not sure if you will get any results anymore - let alone here.
This: https://github.com/Z-Bolt/OctoScreen  -- has the most recent updates to Octoscreen and only by one month. There have not been any changes or updates since the beginning of the year. My guess is this project has been abandoned by it's creator. 
I think your best option is to create your own fork of Octoscreen from the other link and create the changes you need. 
Maybe you could request to take over the project - because someone should and it's a great project. There are many issues unresolved for many months now which would greatly help the community if your fork worked them through.

**Comment by JeffB42** [comment]
@Protean-Man - I contacted Aleksei and he granted me moderator rights.  I just flushed out the LESS and CSS files.  If you install the latest, you will get the update which has no custom CSS stylings.  I'm new to this, and I'm not sure how the versioning works (w/r/t OctoPrint's plugin manager and GitHub).  You might need to uninstall OctoPrint-Z-Bolt-OctoScreen and then reinstall it (using the same URL that's in the readme file, https://github.com/Z-Bolt/OctoPrint-Z-Bolt-OctoScreen/archive/master.zip)
